### ISSUE TITLE
intermittent api outages with error: Redis is configured to save RDB snapshots, but is currently not able to persist on disk.

### ISSUE THREAD

**Issue by jhpoelen** [ropensci/fishbaseapi#105]
As I was updating some fishbase caches using https://github.com/jhpoelen/fishbase_archiver , I found that after a while, the following error message was generated (also see attached screenshot):

"Redis::CommandError at /diet
MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error."

After this error, it seems that non of the api endpoints are operational. Please let me know if you need any more info to figure out what is happening.

![fishbaseapi](https://cloud.githubusercontent.com/assets/1084872/23089808/dbcff8e8-f544-11e6-95f2-c1b083199128.png)

**Comment by sckott** [comment]
@jhpoelen Seems up to me. 

though maybe the `after a while` is the key - what do you mean by that

**Comment by jhpoelen** [comment]
to reproduce:

```
git clone https://github.com/jhpoelen/fishbase_archiver.git
cd fishbase_archiver
bash archive_fishbase.sh > log.txt
```

in attached log.txt, you'll see outage starts after https://fishbase.ropensci.org/sealifebase/larvae?offset=0&limit=5000 (see below). After that, visiting https://fishbase.ropensci.org/heartbeat generated the previously shared error message. Also attached screenshot. Hope this helps.
```
[https://fishbase.ropensci.org/larvae?offset=0&limit=5000] downloaded.
returned: 2876, offset= 5000
[https://fishbase.ropensci.org/larvae?offset=5000&limit=5000] downloading...
[https://fishbase.ropensci.org/larvae?offset=5000&limit=5000] downloaded.
returned: 0, offset= 10000
[https://fishbase.ropensci.org/sealifebase/larvae?offset=0&limit=5000] downloading...
[https://fishbase.ropensci.org/sealifebase/larvae?offset=0&limit=5000] downloaded.
returned: , offset= 5000
```
[log.txt](https://github.com/ropensci/fishbaseapi/files/784791/log.txt)




stderr - 
parse error: Invalid numeric literal at line 1, column 6
archive_fishbase.sh: line 32: [: -gt: unary operator expected
archive_fishbase.sh: line 24: [: -gt: unary operator expected
parse error: Invalid numeric literal at line 1, column 6
archive_fishbase.sh: line 32: [: -gt: unary operator expected
... repeat

![heartbeat](https://cloud.githubusercontent.com/assets/1084872/23090593/28b87002-f556-11e6-9741-db25c7f99105.png)

**Comment by sckott** [comment]
thanks - started to look this weekend, not quite there yet

**Comment by jhpoelen** [comment]
thanks for having a look - where you able to reproduce?

**Comment by sckott** [comment]
yes, but haven't got around to trying for a fix yet, on the list

**Comment by jhpoelen** [comment]
ok, good to hear you were able to reproduce. No rush on my end: I was able to work around the issue and produced some archives, see https://github.com/jhpoelen/fishbase_archiver/releases/tag/v0.2.0 .

**Comment by sckott** [comment]
sorry taking me a while to get to this. 

by the way, we only update the fishbase DB like every 6 months or so, so can't you just grab all the data once and cache it?

**Comment by jhpoelen** [comment]
@sckott no worries about the timing. 

The fishbase/sealifebase table data is actually cached using fishbase_archiver to decouple from the fishbase api :  https://github.com/jhpoelen/fishbase_archiver/releases/tag/v0.2.0 . Using the archives leads to a predictable data ingestion process. The archives are now used by GloBI / globalnames to integrate diet/predator data and taxonomic information.

**Comment by sckott** [comment]
how often do you try to update your cache from this API

**Comment by jhpoelen** [comment]
Right now, I update manually, whenever necessary. In an ideal world, this caching would be triggered whenever fishbase api gets a new fishbase database dump.

**Comment by cboettig** [comment]
I think this should be fixed now, can you try again?

**Comment by jhpoelen** [comment]
@cboettig Thanks for responding... I re-ran the archiver and was able to reproduce the issue (see attached screenshot). So, from what I am seeing, the issue (or similar issue) still exists. Please let me know if you need more info.

![fishbaseapirediserror20170302](https://cloud.githubusercontent.com/assets/1084872/23537704/d46b9c2c-ff82-11e6-9851-2085e0e4d287.png)

**Comment by cboettig** [comment]
@jhpoelen whoops, I I should have re-created the docker container, I had only restarted it.  I think I have persistent disk storage for redis enabled now, can you try once more?

**Comment by jhpoelen** [comment]
@cboettig it appears that some issues remain. Attached screenshot shows redis error page - this time, the request ```https://fishbase.ropensci.org/morphmet?offset=0&limit=5000``` caused the issue, during a running ```./archive_fishbase``` of [fishbase_archiver](https://github.com/jhpoelen/fishbase_archiver) . Please let me know if you need any more info to reproduce.

![fishbaseapiredis20170303](https://cloud.githubusercontent.com/assets/1084872/23562588/f19998ba-fff7-11e6-9e6d-1a29adfc11b3.png)

**Comment by cboettig** [comment]
Interesting.  I can't reproduce so far, at least the above url call works fine for me in the browser.  Progress though, we have a different redis error now.  @sckott any ideas?  Do you think we just need to do something on the API end or some kind of rate limiting step in the Caddy proxy server to give Redis some time reading from disk?   @jhpoelen does this look like a rate-limiting operation to you or are the errors you get persistent?

We're hosting on an EC2 instance which I believe only has EBS-based storage.  Now that we've enabled persistent disk storage for REDIS read times might be significantly slower.   Maybe an SSD-backed instance would alleviate that, though would obviously cost me more...

**Comment by jhpoelen** [comment]
By reproducing I meant running ```./archive_fishbase.sh```. 

The errors I see go away after a while, which explains why hitting a url some time later does not create the same error. From what I can tell, I suspect that there is some caching / cache eviction cycle happening that redis can't keep up with: if a specific cache for a table has been evicted, it takes a while to load it... too long to fulfill a api request, which leads to an error. Again, just speculation. Hope it helps.

**Comment by sckott** [comment]
Looking around for a solution for the redis problem ...

**Comment by cboettig** [comment]
I took a peek at the redis logs and it looks like we're just pounding the server too hard (a bunch of out-of-memory errors, but also a bunch I don't understand:

```
Starting automatic rewriting of AOF on 139% growth
redis_1        | 1:M 03 Mar 06:02:23.261 # Error opening /setting AOF rewrite IPC pipes: Numerical result out of range
```

@sckott maybe there's some clue in there for you in debugging the redis issues?

  @jhpoelen can you try rate-limiting your archive script?  Not sure what we can do on our end, maybe we can rate-limit the api or maybe there's tweaks to get better performance out of our redis config?

**Comment by ojacobson** [comment]
Gauging from the log output, it might be [this Redis bug](https://github.com/antirez/redis/issues/2857), fixed on redis unstable 11 days ago.

**Comment by sckott** [comment]
@cboettig let's try upgrading redis (changes on branch `unstable`), there was a recent fix https://github.com/antirez/redis/commit/9b05aafb50348838f45bfddcd689e7d8d1d3c950 for https://github.com/antirez/redis/issues/2883 and https://github.com/antirez/redis/issues/2857  - couldn't hurt to try even if it doesn't fix

**Comment by sckott** [comment]
i assume this is sorted now
